steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/dinner-is-servered:base || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/base.Dockerfile',
    '-t', 'dinner-is-servered:base',
    '-t', 'gcr.io/$PROJECT_ID/dinner-is-servered:base',
    '--cache-from', 'gcr.io/$PROJECT_ID/dinner-is-servered:base',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/dinner-is-servered:base']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/dinner-is-servered:latest',
    '.'
  ]


- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/coverage.Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/dinner-is-servered:coverage',
    '.'
  ]



images: ['gcr.io/$PROJECT_ID/dinner-is-servered:base', 'gcr.io/$PROJECT_ID/dinner-is-servered:latest', 'gcr.io/$PROJECT_ID/dinner-is-servered:coverage']
